# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 23:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20180206_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 2, 6, 23, 42, 39, 533747)),
        ),
    ]
