# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20180207_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='Device',
            new_name='device',
        ),
    ]
