# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20180207_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='MainApp.Device'),
        ),
        migrations.AlterField(
            model_name='day',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day', to='MainApp.Configuration'),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='MainApp.User'),
        ),
    ]
