# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_auto_20180207_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='time',
        ),
        migrations.AddField(
            model_name='configuration',
            name='hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
